# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  clien-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    name: "Build&Test: node-${{ matrix.node_version }}"
    steps:
      - uses: actions/checkout@v3
      - name: Set node version to ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: cd into client folder
        run: cd ./client
      - name: Install deps
        run: npm install
      - name: Build
        run: npm run build
      - name: CI
        run: npm test
